[versions]
agp = "8.1.2"
kotlin = "1.9.24"
googleServices = "4.4.0"
runtime = "1.0.0-alpha09"

[libraries]
androidx-runtime = { group = "androidx.xr.runtime", name = "runtime", version.ref = "runtime" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }